"""
AfriChess Puzzle Routes
=======================
Add these routes to server.py (or include this as a router).

Provides:
  GET  /api/puzzle/random          → a random puzzle
  GET  /api/puzzle/{id}            → a specific puzzle
  POST /api/puzzle/{id}/attempt    → record an attempt (auth optional)
  GET  /api/puzzle/daily           → the daily puzzle (same for all users)

Puzzles are loaded from puzzles.json (generated by puzzle_gen.py).
If puzzles.json doesn't exist, falls back to the built-in seed set.

Add to server.py:
    from puzzle_routes import puzzle_router
    app.include_router(puzzle_router)
"""

from fastapi import APIRouter, HTTPException, Depends, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import Optional
import json
import random
import os
import subprocess
import tempfile
import re
from datetime import date, datetime
from pathlib import Path

puzzle_router = APIRouter(prefix="/api/puzzle", tags=["puzzles"])

# ── Load puzzle database ───────────────────────────────────────────────────
PUZZLE_FILE = Path(__file__).parent / "puzzles.json"
ENGINE_PATH = Path(__file__).parent / "engines" / "engine"  # matches server.py path
if not ENGINE_PATH.exists():
    # Fallback: try same dir as script (for local dev)
    ENGINE_PATH = Path(__file__).parent / "senkabala"

_PUZZLES: list[dict] = []

def load_puzzles() -> list[dict]:
    global _PUZZLES
    if _PUZZLES:
        return _PUZZLES
    if PUZZLE_FILE.exists():
        with open(PUZZLE_FILE) as f:
            _PUZZLES = json.load(f)
    else:
        # Fallback: built-in tactical puzzles (always available)
        _PUZZLES = BUILTIN_PUZZLES
    return _PUZZLES

# Built-in puzzle set — always available, no file needed
BUILTIN_PUZZLES = [
    {
        "id": "builtin_001",
        "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
        "best_move": "f3g5",
        "score_cp": 300,
        "pv": ["f3g5", "d8e7", "g5f7"],
        "type": "Fork",
        "description": "Attack two pieces simultaneously.",
        "rating": 2,
        "gap_cp": 200,
    },
    {
        "id": "builtin_002",
        "fen": "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
        "best_move": "e1e8",
        "score_cp": 29999,
        "pv": ["e1e8"],
        "type": "Mate in 1",
        "description": "Find the forced checkmate in 1 move.",
        "rating": 1,
        "gap_cp": 999,
    },
    {
        "id": "builtin_003",
        "fen": "r3k2r/pppq1ppp/2np1n2/2b1p3/2B1P1b1/2NP1N2/PPPQ1PPP/R3K2R w KQkq - 0 8",
        "best_move": "f3e5",
        "score_cp": 250,
        "pv": ["f3e5", "c5e3", "e5d7"],
        "type": "Fork",
        "description": "Knight fork winning material.",
        "rating": 2,
        "gap_cp": 180,
    },
    {
        "id": "builtin_004",
        "fen": "8/8/8/8/8/k7/p7/K7 b - - 0 1",
        "best_move": "a2a1q",
        "score_cp": 29000,
        "pv": ["a2a1q"],
        "type": "Promotion",
        "description": "Promote the pawn to queen and win.",
        "rating": 1,
        "gap_cp": 999,
    },
    {
        "id": "builtin_005",
        "fen": "rnb1kbnr/pppp1ppp/8/4p3/6Pq/5P2/PPPPP2P/RNBQKBNR w KQkq - 1 3",
        "best_move": "g4g5",  # only legal move that blocks
        "score_cp": -500,
        "pv": ["g4g5"],
        "type": "Defensive",
        "description": "Find the only move to avoid immediate checkmate.",
        "rating": 2,
        "gap_cp": 300,
    },
]


# ── Engine analysis helper ─────────────────────────────────────────────────
def analyse_fen(fen: str, movetime_ms: int = 1500) -> dict:
    """
    Run SenkabalaIII on a FEN and return best_move + score_cp.
    Used for the /verify endpoint and on-the-fly puzzle generation.
    """
    if not ENGINE_PATH.exists():
        return {"best_move": None, "score_cp": 0, "error": "Engine not found"}

    try:
        proc = subprocess.Popen(
            [str(ENGINE_PATH)],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True, bufsize=1,
        )

        def send(cmd):
            proc.stdin.write(cmd + "\n")
            proc.stdin.flush()

        send("uci")
        send("setoption name Hash value 32")
        send("isready")
        send(f"position fen {fen}")
        send(f"go movetime {movetime_ms}")

        best_move = None
        score_cp  = 0
        import time
        deadline = time.time() + 8.0

        while time.time() < deadline:
            line = proc.stdout.readline().strip()
            if line.startswith("info"):
                m = re.search(r"\bscore cp (-?\d+)", line)
                if m:
                    score_cp = int(m.group(1))
                mm = re.search(r"\bscore mate (-?\d+)", line)
                if mm:
                    score_cp = 29000 if int(mm.group(1)) > 0 else -29000
            elif line.startswith("bestmove"):
                parts = line.split()
                best_move = parts[1] if len(parts) > 1 else None
                break

        send("quit")
        proc.wait(timeout=2)

        return {"best_move": best_move, "score_cp": score_cp}
    except Exception as e:
        return {"best_move": None, "score_cp": 0, "error": str(e)}


# ── Endpoints ──────────────────────────────────────────────────────────────

@puzzle_router.get("/random")
async def random_puzzle(tactic: Optional[str] = None, rating: Optional[int] = None):
    """
    GET /api/puzzle/random
    Optional filters: ?tactic=Fork&rating=2
    Returns a random puzzle matching filters.
    """
    puzzles = load_puzzles()
    pool = puzzles

    if tactic:
        pool = [p for p in pool if tactic.lower() in p.get("type", "").lower()]
    if rating is not None:
        pool = [p for p in pool if p.get("rating") == rating]

    if not pool:
        pool = puzzles  # ignore filters if nothing matches

    puzzle = random.choice(pool)
    # Never expose the solution in the initial response
    return _sanitise(puzzle)


@puzzle_router.get("/daily")
async def daily_puzzle():
    """
    GET /api/puzzle/daily
    Returns today's puzzle (same for all users, changes at midnight EAT).
    Seeded by date so it's deterministic.
    """
    puzzles = load_puzzles()
    today = date.today().toordinal()
    puzzle = puzzles[today % len(puzzles)]
    return {**_sanitise(puzzle), "is_daily": True, "date": str(date.today())}


@puzzle_router.get("/{puzzle_id}")
async def get_puzzle(puzzle_id: str):
    """GET /api/puzzle/{id}"""
    puzzles = load_puzzles()
    for p in puzzles:
        if p["id"] == puzzle_id:
            return _sanitise(p)
    raise HTTPException(status_code=404, detail="Puzzle not found")


class AttemptBody(BaseModel):
    move:      str       # UCI move played by user, e.g. "e2e4"
    time_ms:   int = 0   # how long they took
    hint_used: bool = False


@puzzle_router.post("/{puzzle_id}/attempt")
async def attempt_puzzle(puzzle_id: str, body: AttemptBody, request: Request):
    """
    POST /api/puzzle/{id}/attempt
    Body: { "move": "e2e4", "time_ms": 3200 }
    Returns: { "correct": true/false, "solution": "e2e4", "explanation": "..." }

    Records attempt in Supabase if user is authenticated.
    """
    puzzles = load_puzzles()
    puzzle = next((p for p in puzzles if p["id"] == puzzle_id), None)
    if not puzzle:
        raise HTTPException(status_code=404, detail="Puzzle not found")

    correct = body.move.lower() == puzzle["best_move"].lower()

    # Optional: record to Supabase (requires auth header)
    # auth_header = request.headers.get("Authorization")
    # if auth_header: await record_attempt(puzzle_id, body.move, correct, auth_header)

    return {
        "correct":     correct,
        "solution":    puzzle["best_move"] if not correct else None,
        "pv":          puzzle["pv"],
        "score_cp":    puzzle["score_cp"],
        "type":        puzzle["type"],
        "explanation": _explain(puzzle, correct),
    }


@puzzle_router.get("/list/all")
async def list_puzzles(
    tactic: Optional[str] = None,
    rating: Optional[int] = None,
    limit: int = 20,
    offset: int = 0,
):
    """GET /api/puzzle/list/all — paginated puzzle list."""
    puzzles = load_puzzles()
    pool = puzzles

    if tactic:
        pool = [p for p in pool if tactic.lower() in p.get("type", "").lower()]
    if rating is not None:
        pool = [p for p in pool if p.get("rating") == rating]

    total = len(pool)
    page  = pool[offset:offset + limit]

    return {
        "total":   total,
        "offset":  offset,
        "limit":   limit,
        "puzzles": [_sanitise(p) for p in page],
    }


# ── On-the-fly puzzle from FEN ─────────────────────────────────────────────
class FENBody(BaseModel):
    fen: str
    movetime_ms: int = 1500


@puzzle_router.post("/from-fen")
async def puzzle_from_fen(body: FENBody):
    """
    POST /api/puzzle/from-fen
    Body: { "fen": "...", "movetime_ms": 2000 }
    Returns: best_move, score_cp, tactic type.
    Useful for creating puzzles from your own games.
    """
    result = analyse_fen(body.fen, movetime_ms=body.movetime_ms)
    if result.get("error"):
        raise HTTPException(status_code=503, detail=result["error"])

    best_move = result["best_move"]
    score_cp  = result["score_cp"]

    if not best_move:
        raise HTTPException(status_code=422, detail="Engine returned no move")

    from puzzle_gen import classify_tactic
    tactic = classify_tactic(body.fen, best_move, score_cp, [best_move])

    return {
        "fen":       body.fen,
        "best_move": best_move,
        "score_cp":  score_cp,
        "type":      tactic["type"],
        "description": tactic["description"],
    }


# ── Helpers ────────────────────────────────────────────────────────────────
def _sanitise(puzzle: dict) -> dict:
    """Strip solution from puzzle data for initial delivery."""
    return {k: v for k, v in puzzle.items() if k not in ("best_move", "pv")}


def _explain(puzzle: dict, correct: bool) -> str:
    ptype = puzzle.get("type", "Tactical")
    desc  = puzzle.get("description", "")
    score = puzzle.get("score_cp", 0)

    if correct:
        if score >= 29000:
            return f"Excellent! That's checkmate. {desc}"
        return f"Correct! {desc} This move wins {score/100:.1f} pawns of material."
    else:
        if score >= 29000:
            return f"Not quite. The winning move leads to forced checkmate. {desc}"
        return f"Not the best move. The correct idea was: {desc}"
